print(" My daily routine ") 
print(" I wake up at 6 am for school ")
print(" I have breakfast ")
print(" I leave for school at 8 ")
print(" I leave for home at 3 ")
print(" I do homework ")
print(" I eat dinner with my family ")
print(" I watch tv ")
print(" I go to sleep ")